name: Build & Deploy to Production

# Run when a dispatch event is created (e.g. from a CMS Webhook)
# See https://developer.github.com/v3/repos/#create-a-repository-dispatch-event
on: 
  repository_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v1 # Equivalent to `git checkout master`
    
        - name: Setup Node
          uses: actions/setup-node@v1.4.2
          with:
              node-version: '12.x'

        - name: install dependencies
          run: npm install
        
        - name: Deploy
          run: npm run deploy
          env: 
            CONTENTFUL_SPACE_ID: "i4saea19036k"
            CONTENTFUL_ACCESS_KEY: "8wse3Ujh3ArWjuOTMLeWW2dXS5eSJn_Agjl2JEk6Ftc"